# Facil
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
SIGNING_KEY = "GC2552U75M664XAUUKXNMF7ATOW6XOF3IGH2CBLHYEF35WDXHJHEIZDW"
FEDERATION_SERVER="https://api.vesseoapp.com/federation"

[[CURRENCIES]]
code = "USDC"
issuer = "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"
status = "test"
is_asset_anchored = true
anchor_asset_type = "fiat"
desc = "A test USDC issued by Circle."

[DOCUMENTATION]
ORG_NAME = "MoneyGram"
ORG_URL = "https://www.moneygram.com"
ORG_DESCRIPTION = "MoneyGram"
ORG_TWITTER = "MoneyGram"
ORG_GITHUB = "MoneyGram"